use_frameworks!

platform :ios, '8.0'

target 'FAPI_Example' do
  pod 'FAPI', :path => '../'

  target 'FAPI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
